# Generated by Django 4.1 on 2022-09-26 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('lastname', models.CharField(max_length=30, verbose_name='Lastname')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('document', models.CharField(max_length=15, unique=True, verbose_name='Document')),
                ('telephone', models.CharField(max_length=20, verbose_name='Telephone')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('gender', models.CharField(max_length=1, verbose_name='Gender')),
                ('isactive', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='tabla_Enfermedad',
            fields=[
                ('id_Enfermedad', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Enfermedad', models.TextField(max_length=20, unique=True, verbose_name='Enfermedad')),
                ('Descripcion_Enfermedad', models.TextField(max_length=200, unique=True, verbose_name='Descripciondeenfermedad')),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Tabla_Vacunas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=4, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('age', models.IntegerField(default=0)),
                ('race', models.CharField(max_length=30, verbose_name='Race')),
                ('sex', models.CharField(max_length=1, verbose_name='Sex')),
                ('species', models.CharField(max_length=30, verbose_name='Species')),
                ('features', models.CharField(max_length=30, verbose_name='Features')),
                ('isactive', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petclient', to='api.client')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ClientOwner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('lastname', models.CharField(max_length=30, verbose_name='Lastname')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('document', models.CharField(max_length=15, unique=True, verbose_name='Document')),
                ('telephone', models.CharField(max_length=20, verbose_name='Telephone')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('gender', models.CharField(max_length=1, verbose_name='Gender')),
                ('isactive', models.BooleanField(default=True)),
                ('typedocument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientowner', to='api.typedocument')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='typedocument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='typedocclient', to='api.typedocument'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('lastname', models.CharField(max_length=30, verbose_name='Lastname')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('document', models.CharField(max_length=15, unique=True, verbose_name='Document')),
                ('telephone', models.CharField(max_length=20, verbose_name='Telephone')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('gender', models.CharField(max_length=1, verbose_name='Gender')),
                ('isactive', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('typedocument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='typedocument', to='api.typedocument')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
