# Generated by Django 4.1 on 2022-09-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typedocument',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='code',
            field=models.CharField(max_length=4, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15, unique=True, verbose_name='Username'),
        ),
    ]
