# Generated by Django 4.1 on 2022-09-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOwner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('lastname', models.CharField(max_length=30, verbose_name='Lastname')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('document', models.CharField(max_length=15, unique=True, verbose_name='Document')),
                ('telephone', models.CharField(max_length=20, verbose_name='Telephone')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('gender', models.CharField(max_length=1, verbose_name='Gender')),
                ('isactive', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
