# Generated by Django 4.1 on 2022-09-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='vaccine',
            field=models.ManyToManyField(related_name='petvaccine', to='api.tabla_vacunas'),
        ),
    ]
