# Generated by Django 4.1 on 2022-09-26 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pet_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petclient', to='api.clientowner'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
