# Generated by Django 4.1 on 2022-09-22 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clientowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientowner',
            name='typedocument',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='typedocclientowner', to='api.typedocument'),
            preserve_default=False,
        ),
    ]
