# Generated by Django 4.1 on 2022-09-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_typedocument_name_alter_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Name')),
            ],
        ),
    ]
