# Generated by Django 4.1 on 2022-09-26 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pet_client_delete_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='vaccine',
        ),
    ]
