# Generated by Django 4.1 on 2022-09-20 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tabla_Enfermedad'),
        ('api', '0003_tabla_servicio'),
        ('api', '0003_tabla_vacunas'),
    ]

    operations = [
    ]
