# Generated by Django 4.1 on 2022-09-28 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_pet_vaccine'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetVacinne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccinepet', to='api.pet')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccinevaccine', to='api.tabla_vacunas')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
