# Generated by Django 4.1 on 2022-09-28 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_petvacinne'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('fecha', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ritmocardiaco', models.IntegerField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ConsultaPet', to='api.pet')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
