# Generated by Django 4.1 on 2022-09-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_consultamedica'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultamedica',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
