from .typeDocument import TypeDocument
from .user import User
from .servicio import Tabla_Servicio
from .Enfermedad import tabla_Enfermedad
from .pet import Pet
from .vaccines import Tabla_Vacunas
from .clientOwner import ClientOwner
from .petVaccine import PetVacinne
from .consultaMedica import ConsultaMedica