import imp
from .typeDocumentSerializer import TypeDocumentSerializer
from .userSerializer import UserSerializer
from .vaccinesSerializer import VaccinesSerializer
from .servicioSerializer import servicioSerializer
from .petSerializer import PetSerializer
from .enfermedadSerializer import EnfermedadSerializer
from .clientSerializer import ClientSerializer
from .clientOwnerSerializer import ClientOwnerSerializer